# k8s/resources-demo.yaml 

apiVersion: v1
kind: Pod
metadata:
  name: game
  labels:
    app: game
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
    resources:
      requests:
        cpu: 50m
        memory: 5Mi
      limits:
        cpu: 1000m
        memory: 1280Mi
  initContainers:
    - name: init
      image: ubuntu:latest
      volumeMounts:
        - name: html
          mountPath: /home/ubuntu/game
      resources:
        requests:
          cpu: 50m
          memory: 5Mi
        limits:
          cpu: 1000m
          memory: 1280Mi
      command:
          - /bin/bash
          - -c
          - |
            #!/bin/bash
            apt-get update && apt-get install -y git
            git clone https://github.com/gabrielecirulli/2048.git /home/ubuntu/game

  volumes:
    - name: html
      emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: game
  ports:
  - port: 9876
    targetPort: 80
