apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-redis
  name: grafana-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grafana-redis
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "750Mi"
            cpu: "500m"
        env:
          - name: "GF_AUTH_BASIC_ENABLED"
            value: "true"

          - name: "GF_SECURITY_ADMIN_USER"
            valueFrom:
              secretKeyRef:
                key: GF_SECURITY_ADMIN_USER
                name: grafana-secrets
          - name: "GF_SECURITY_ADMIN_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: GF_SECURITY_ADMIN_PASSWORD
                name: grafana-secrets
          - name: "GF_INSTALL_PLUGINS"
            value: "redis-datasource"
status: {}
---

apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  selector:
    app: grafana-redis
  ports:
  - port: 3000
    targetPort: 3000
